alias goev='cd /home/erova'
alias gorun='cd /home/erova/runway'
alias puprun='sudo puppet agent -t'
alias puptest='sudo puppet agent -t --verbose --noop'
alias tlogs='tail -F /var/log/syslog'
alias pychecks='ps aux | grep python'
