FROM php:7.1.21-apache-jessie
COPY src/index.html /var/www/html
COPY src/apache2/sites-enabled/ /etc/apache2/sites-enabled/
COPY src/apache2/sites-available/ /etc/apache2/sites-available/

EXPOSE 80 
